// Generated by Wrangler by running `wrangler types`

interface Env {
	HAA_KV: KVNamespace;
	GOOGLE_AUTH_CLIENT: string;
	GOOGLE_AUTH_SECRET: string;
	GOOGLE_AUTH_CALLBACK_URL: string;
	D1_ACCOUNT_ID: string;
	D1_ID: string;
	D1_TOKEN: string;
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_URL: string;
	TURSO_DATABASE_URL: string;
	TURSO_AUTH_TOKEN: string;
	DB: D1Database;
}
