# name: Deploy to Cloudflare Pages

# on:
#   push:
#     branches:
#       - master  # Run workflow when pushing to master

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
    
#     env:
#       BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
#       BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}
#       GOOGLE_AUTH_CALLBACK_URL: ${{ secrets.GOOGLE_AUTH_CALLBACK_URL }}
#       GOOGLE_AUTH_CLIENT: ${{ secrets.GOOGLE_AUTH_CLIENT }}
#       GOOGLE_AUTH_SECRET: ${{ secrets.GOOGLE_AUTH_SECRET }}
#       KEYSTATIC_GITHUB_CLIENT_ID: ${{ secrets.KEYSTATIC_GITHUB_CLIENT_ID }}
#       KEYSTATIC_GITHUB_CLIENT_SECRET: ${{ secrets.KEYSTATIC_GITHUB_CLIENT_SECRET }}
#       KEYSTATIC_SECRET: ${{ secrets.KEYSTATIC_SECRET }}
#       RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
#       TURNSTILE_SECRET_KEY: ${{ secrets.TURNSTILE_SECRET_KEY }}
#       TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
#       TURSO_DATABASE_URL: ${{ secrets.TURSO_DATABASE_URL }}
#       PUBLIC_KEYSTATIC_GITHUB_APP_SLUG: ${{ vars.PUBLIC_KEYSTATIC_GITHUB_APP_SLUG }}
#       PUBLIC_TURNSTILE_SITE_KEY: ${{ vars.PUBLIC_TURNSTILE_SITE_KEY }}
#       CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      
    
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20  # Adjust based on your project requirements

#       - name: Install dependencies
#         run: npm install

#       - name: Run deploy script
#         run: npm run deploy
